name: Continuous integration

# Running on the branch main and on all PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous_integration:
    name: Continuous integration
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python with the version from the .python-version file
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip' # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check format of Python code
        run: ruff format --check --diff

      - name: Lint Python code
        run: ruff check

      - name: Run tests
        run: make tests
